"use client";
import { useEffect, useRef, useState, useMemo } from "react";
import { Navbar } from "@/components/ui/Navbar";
import { CATEGORIES } from "@/lib/types";
import type { Place, CategorySlug } from "@/lib/types";
import { Search, X, MapPin, Star } from "lucide-react";
const POIS=[{name:"Praia",type:"city",lat:14.9315,lng:-23.5135,emoji:"🏙️"},{name:"Assomada",type:"city",lat:15.0968,lng:-23.6681,emoji:"🏙️"},{name:"Pedra Badejo",type:"city",lat:15.1389,lng:-23.5336,emoji:"🏙️"},{name:"Tarrafal",type:"city",lat:15.2781,lng:-23.7519,emoji:"🏙️"},{name:"São Domingos",type:"city",lat:15.0208,lng:-23.5644,emoji:"🏙️"},{name:"Santa Cruz",type:"city",lat:15.1258,lng:-23.5258,emoji:"🏙️"},{name:"Praia do Tarrafal",type:"beach",lat:15.2890,lng:-23.7580,emoji:"🏖️"},{name:"Praia de São Francisco",type:"beach",lat:14.9450,lng:-23.5200,emoji:"🏖️"},{name:"Praia de Quebra Canela",type:"beach",lat:14.9368,lng:-23.5100,emoji:"🏖️"},{name:"Praia Baixo",type:"beach",lat:15.1100,lng:-
mkdir -p apps/web/src/app/mapa && cat > apps/web/src/app/mapa/MapClient.tsx << 'EOF'
"use client";
import { useEffect, useRef, useState, useMemo } from "react";
import { Navbar } from "@/components/ui/Navbar";
import { CATEGORIES } from "@/lib/types";
import type { Place, CategorySlug } from "@/lib/types";
import { Search, X, MapPin, Star } from "lucide-react";
const POIS=[{name:"Praia",type:"city",lat:14.9315,lng:-23.5135,emoji:"🏙️"},{name:"Assomada",type:"city",lat:15.0968,lng:-23.6681,emoji:"🏙️"},{name:"Pedra Badejo",type:"city",lat:15.1389,lng:-23.5336,emoji:"🏙️"},{name:"Tarrafal",type:"city",lat:15.2781,lng:-23.7519,emoji:"🏙️"},{name:"São Domingos",type:"city",lat:15.0208,lng:-23.5644,emoji:"🏙️"},{name:"Santa Cruz",type:"city",lat:15.1258,lng:-23.5258,emoji:"🏙️"},{name:"Praia do Tarrafal",type:"beach",lat:15.2890,lng:-23.7580,emoji:"🏖️"},{name:"Praia de São Francisco",type:"beach",lat:14.9450,lng:-23.5200,emoji:"🏖️"},{name:"Praia de Quebra Canela",type:"beach",lat:14.9368,lng:-23.5100,emoji:"🏖️"},{name:"Praia Baixo",type:"beach",lat:15.1100,lng:-23.5050,emoji:"🏖️"},{name:"Cidade Velha",type:"historic",lat:14.9167,lng:-23.6050,emoji:"🏛️"},{name:"Pelourinho",type:"historic",lat:14.9155,lng:-23.6046,emoji:"🗿"},{name:"Fortaleza Real de S. Filipe",type:"historic",lat:14.9120,lng:-23.6090,emoji:"⚔️"},{name:"Campo Concentração Tarrafal",type:"historic",lat:15.2820,lng:-23.7500,emoji:"🏛️"},{name:"Pico de Antónia 1394m",type:"nature",lat:15.0600,lng:-23.6400,emoji:"⛰️"},{name:"Serra Malagueta",type:"nature",lat:15.1300,lng:-23.7000,emoji:"🌿"},{name:"Aeroporto Amílcar Cabral",type:"infra",lat:14.9245,lng:-23.4934,emoji:"✈️"},{name:"Porto da Praia",type:"infra",lat:14.9210,lng:-23.5050,emoji:"⚓"},{name:"Mercado de Sucupira",type:"infra",lat:14.9300,lng:-23.5120,emoji:"🛒"}];
const POI_COLOR:Record<string,string>={city:"#0B5E8A",beach:"#14B8A6",historic:"#92400E",nature:"#15803D",infra:"#374151"};
function loadLeaflet():Promise<void>{return new Promise((resolve)=>{if(!document.getElementById("leaflet-css")){const l=document.createElement("link");l.id="leaflet-css";l.rel="stylesheet";l.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";document.head.appendChild(l);}if((window as any).L){resolve();return;}const ex=document.getElementById("leaflet-js");if(ex){ex.addEventListener("load",()=>resolve());return;}const s=document.createElement("script");s.id="leaflet-js";s.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";s.async=true;s.onload=()=>resolve();document.head.appendChild(s);});}
export function MapClient({places}:{places:Place[]}){
const mapRef=useRef<any>(null);const containerRef=useRef<HTMLDivElement>(null);
const markersRef=useRef<any[]>([]);const poiRef=useRef<any[]>([]);
const [ready,setReady]=useState(false);const [sel,setSel]=useState<Place|null>(null);
const [cat,setCat]=useState<CategorySlug|"all">("all");const [q,setQ]=useState("");const [poi,setPoi]=useState(true);
const filtered=useMemo(()=>{let r=places;if(cat!=="all")r=r.filter(p=>p.category_slug===cat);if(q.trim()){const s=q.toLowerCase();r=r.filter(p=>p.name.toLowerCase().includes(s)||p.address.toLowerCase().includes(s));}return r;},[places,cat,q]);
useEffect(()=>{let dead=false;loadLeaflet().then(()=>{if(dead||!containerRef.current)return;const L=(window as any).L;if(mapRef.current){mapRef.current.remove();mapRef.current=null;}const c=containerRef.current as any;if(c._leaflet_id)c._leaflet_id=null;const map=L.map(containerRef.current,{center:[15.07,-23.62],zoom:10,zoomControl:false});L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:19}).addTo(map);L.control.zoom({position:"bottomright"}).addTo(map);L.control.scale({imperial:false,position:"bottomleft"}).addTo(map);mapRef.current=map;if(!dead)setReady(true);});return()=>{dead=true;if(mapRef.current){mapRef.current.remove();mapRef.current=null;}setReady(false);};},[]);
useEffect(()=>{if(!ready||!mapRef.current)return;const L=(window as any).L;const map=mapRef.current;markersRef.current.forEach(m=>m.remove());markersRef.current=[];filtered.forEach(place=>{if(!place.lat||!place.lng)return;const c=CATEGORIES.find(x=>x.slug===place.category_slug);const color=c?.color??"#0B5E8A";const emoji=c?.emoji??"📍";const icon=L.divIcon({className:"",iconSize:[38,38],iconAnchor:[19,38],popupAnchor:[0,-40],html:`<div style="background:${color};border:2.5px solid white;border-radius:50% 50% 50% 0;transform:rotate(-45deg);width:36px;height:36px;display:flex;align-items:center;justify-content:center;box-shadow:0 4px 14px rgba(0,0,0,0.3);cursor:pointer"><span style="transform:rotate(45deg);font-size:16px">${emoji}</span></div>`});const popup=L.popup({maxWidth:240,closeButton:true}).setContent(`<div style="font-family:sans-serif;padding:4px">${place.cover_url?`<img src="${place.cover_url}" style="width:100%;height:80px;object-fit:cover;border-radius:10px;margin-bottom:8px"/>`:"" }<div style="font-size:11px;color:${color};font-weight:600">${emoji} ${c?.label??""}</div><div style="font-weight:700;font-size:14px;color:#0B2E4A">${place.name}</div><div style="font-size:12px;color:#6B7280">📍 ${place.address}</div><div style="font-size:12px">⭐ ${place.rating.toFixed(1)} (${place.review_count})</div></div>`);const marker=L.marker([place.lat,place.lng],{icon}).addTo(map).bindPopup(popup);marker.on("click",()=>setSel(place));markersRef.current.push(marker);});},[filtered,ready]);
useEffect(()=>{if(!ready||!mapRef.current)return;const L=(window as any).L;const map=mapRef.current;poiRef.current.forEach(m=>m.remove());poiRef.current=[];if(!poi)return;POIS.forEach(p=>{const color=POI_COLOR[p.type]??"#6B7280";const icon=L.divIcon({className:"",iconSize:[28,28],iconAnchor:[14,28],popupAnchor:[0,-30],html:`<div style="background:white;border:2px solid ${color};border-radius:50%;width:26px;height:26px;display:flex;align-items:center;justify-content:center;box-shadow:0 2px 8px rgba(0,0,0,0.2);font-size:13px">${p.emoji}</div>`});const marker=L.marker([p.lat,p.lng],{icon,zIndexOffset:-10}).addTo(map).bindPopup(`<div style="font-family:sans-serif;padding:4px"><b>${p.emoji} ${p.name}</b><div style="font-size:11px;color:${color}">${p.type}</div></div>`);poiRef.current.push(marker);});},[ready,poi]);
const activeCat=cat!=="all"?CATEGORIES.find(c=>c.slug===cat):null;
return(<div className="flex flex-col h-screen overflow-hidden">
<Navbar/>
<div className="z-10 bg-white border-b border-ocean/10 px-4 py-3 flex flex-wrap items-center gap-3 shadow-sm">
<div className="relative flex-1 min-w-[180px] max-w-xs"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar locais…" className="w-full pl-9 pr-4 py-2 rounded-xl border border-ocean/15 text-sm focus:outline-none focus:ring-2 focus:ring-ocean/30 bg-sand-light"/>{q&&<button onClick={()=>setQ("")} className="absolute right-2 top-1/2 -translate-y-1/2"><X className="w-3.5 h-3.5"/></button>}</div>
<div className="flex items-center gap-1.5 flex-wrap">
<button onClick={()=>setCat("all")} className={`px-3 py-1.5 rounded-full text-xs font-semibold transition-all ${cat==="all"?"bg-ocean text-white":"bg-sand text-ocean-dark hover:bg-ocean/10"}`}>Todos</button>
{CATEGORIES.map(c=><button key={c.slug} onClick={()=>setCat(cat===c.slug?"all":c.slug)} className={`px-3 py-1.5 rounded-full text-xs font-semibold transition-all ${cat===c.slug?"text-white":"bg-sand text-ocean-dark"}`} style={cat===c.slug?{backgroundColor:c.color}:{}}>{c.emoji} {c.label}</button>)}
</div>
<button onClick={()=>setPoi(!poi)} className={`ml-auto flex items-center gap-1 px-3 py-1.5 rounded-full text-xs font-semibold border transition-all ${poi?"bg-ocean/10 border-ocean/30 text-ocean":"bg-sand border-ocean/10 text-muted"}`}><MapPin className="w-3.5 h-3.5"/>POI</button>
</div>
<div className="relative flex-1 overflow-hidden">
<div ref={containerRef} className="w-full h-full"/>
{!ready&&<div className="absolute inset-0 bg-sand-light flex items-center justify-center z-20"><div className="text-center"><div className="text-5xl mb-4 animate-bounce">🗺️</div><p className="font-semibold text-ocean-dark text-lg">A carregar o mapa de Santiago…</p><p className="text-sm text-muted mt-1">Ilha de Santiago · Cabo Verde 🇨🇻</p></div></div>}
{ready&&<div className="absolute top-4 left-4 z-10 bg-white/95 backdrop-blur-sm rounded-2xl shadow-card px-4 py-2.5 flex items-center gap-2"><MapPin className="w-4 h-4 text-ocean"/><span className="font-semibold text-sm text-ocean-dark">{filtered.length} locais</span>{activeCat&&<span className="text-xs px-2 py-0.5 rounded-full text-white" style={{backgroundColor:activeCat.color}}>{activeCat.emoji} {activeCat.label}</span>}</div>}
</div>
{sel&&<div className="absolute bottom-0 left-0 right-0 z-20 bg-white rounded-t-3xl shadow-2xl p-5 border-t border-ocean/10">
<div className="flex items-start gap-3">{(()=>{const c=CATEGORIES.find(x=>x.slug===sel.category_slug);return(<><div className="flex-1"><div className="text-xs font-semibold mb-1" style={{color:c?.color}}>{c?.emoji} {c?.label}</div><h3 className="font-bold text-ocean-dark text-xl mb-1">{sel.name}</h3><p className="text-sm text-muted mb-2">📍 {sel.address}</p><div className="flex items-center gap-2 text-sm"><Star className="w-4 h-4 text-amber-400 fill-amber-400"/><span className="font-semibold">{sel.rating.toFixed(1)}</span><span className="text-muted">({sel.review_count})</span></div>{sel.description&&<p className="text-sm text-ocean-dark/80 mt-2">{sel.description}</p>}</div>{sel.cover_url&&<img src={sel.cover_url} alt={sel.name} className="w-24 h-24 rounded-2xl object-cover shrink-0"/>}<button onClick={()=>setSel(null)} className="w-8 h-8 rounded-full bg-sand flex items-center justify-center"><X className="w-4 h-4"/></button></>);})()}</div>
</div>}
</div>);
}
